### ISSUE TITLE
Not seeing selectScenario take effect during test suite

### ISSUE THREAD

**Issue by jonathan-fw** [ng-apimock/protractor-plugin#5]
Hello,

I'm using ng-apimock in protractor. Here is the current version in my package.json:
`"@ng-apimock/core": "^1.0.21",
  "@ng-apimock/dev-interface": "^1.0.6",
  "@ng-apimock/protractor-plugin": "^1.0.14",`

My instance of ng-apimock is up an running. I can switch scenarios from the UI. However using
`ngApimock.selectScenario(NAME, SCENARIO);` doesn't appear to work. It appears to be at the last scenario I've selected manually. I think it is configured correctly only because if I change the call to a mock name that doesn't exist, it does throw an error.
`UnhandledPromiseRejectionWarning: Error: An error occured while invoking http://localhost:9900/ngapimock/mocks that resulted in status code 409
    at fetchResponse.then (/app/node_modules/@ng-apimock/base-client/src/base.client.ts:121:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:3754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3754) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Since selectScenario returns a promise, I tried using it in browser.wait, but I also got the same issue.

I'm at a loss at what to do to resolve this issue. I can provide any more context that is needed.

**Comment by jonathan-fw** [comment]
I've been looking into this deeper and if I have the right understanding, selectScenario works by setting a cookie on protractor and somehow that leads to changing the scenario on different tests. My understanding based on https://github.com/mdasberg/ng-apimock/issues/48 is that the mocks have to be on the same port as webserver.

This is an issue for my setup because my webserver and the apimock server are on different ports. Webserver is on 8080 while api is on 9900.

Is my resolution simply to add a proxy in protractor for the apis to be on 8080?

**Comment by mdasberg** [comment]
@jonathan-fw yes. You can either add a proxy in protractor or use the proxy functionality of angular or any connect server.

**Comment by jonathan-fw** [comment]
Could this be documented in the readme clearly? I'm pretty sure I'm not the only one that would have this issue.

**Comment by klubi** [comment]
@jonathan-fw I have similar setup to the one mentioned above.
Difference in my case is that not only port is different, but also domains (UI runs https on one domain, mocks are on https with different domain and different port).

I can't get this setup to work, I always get default response.
