### ISSUE TITLE
Possibility to use variables in body matching?

### ISSUE THREAD

**Issue by jonathan-fw** [ng-apimock/protractor-plugin#8]
This might be more of a feature request, but in trying to reduce number of mocks I have created, I attempted to use a variable in the expected body response, but this seems to not work.

example:
`{
  "isArray": true,
  "name": "something_patch",
  "request": {
    "headers": {},
    "method": "PATCH",
    "url": "/api/something/.*/somethingelse/.*",
    "body": {
      "var1": "%%var1_expected%%",
      "var2": true
    }
  }, rest_of_json`

**Comment by mdasberg** [comment]
That feature is not implemented atm. You can use a regular expression to match your body variable.

Is that an option for you?
